### ISSUE TITLE
the results of retrieval 

### ISSUE THREAD

**Issue by danyaljj** [eladsegal/strategyqa#5]
Hey @eladsegal, @mega002 👋 

Wondering if the results of retrieval (say, [top 10 documents](https://github.com/eladsegal/strategyqa#recall10) for the instances in train and evals) are available somewhere? 

I know the instructions for [building a retrieval index](https://github.com/eladsegal/strategyqa/tree/main/elasticsearch_index) are in the repo, however, it's not an easy process. Having the retrieved document accessible can make any future adoption easier. 

FYI @yeganehkordi

**Comment by eladsegal** [comment]
Hey @danyaljj!
The top 10 paragraphs for each question in the official training set (which in this repository is split to `train.json` and `dev.json`) are available in https://github.com/eladsegal/strategyqa/blob/a330fe4ebfa42b05c694bbd9ada1fee9110a130e/data/strategyqa/queries_cache.json. 

As for the gold paragraphs, they are available in https://github.com/eladsegal/strategyqa/blob/a330fe4ebfa42b05c694bbd9ada1fee9110a130e/data/strategyqa/strategyqa_train_paragraphs.json.

In https://github.com/eladsegal/strategyqa/blob/a330fe4ebfa42b05c694bbd9ada1fee9110a130e/src/data/dataset_readers/strategy_qa_reader.py you can see usage examples of these files via `get_elasticsearch_results` for `queries_cache.json` and `get_elasticsearch_paragraph` for `strategyqa_train_paragraphs.json`.

**Comment by danyaljj** [comment]
Thanks! 

> The top 10 paragraphs for each question in the official training set (which in this repository is split to train.json and dev.json) are available in https://github.com/eladsegal/strategyqa/blob/a330fe4ebfa42b05c694bbd9ada1fee9110a130e/data/strategyqa/queries_cache.json 

Does this cache also contain the retrieved documents using the test questions? 
I suppose we needed the retrieved documents to evaluate the model (trained with IR paragraphs) on the test examples.

**Comment by danyaljj** [comment]
@eladsegal pinging the thread, in case it went unnoticed.

**Comment by eladsegal** [comment]
Thanks, I did miss it!
The cache only contains retrieved documents for the train questions, but it does make sense to provide it for test as well.
I will update `queries_cache.json`.

**Comment by danyaljj** [comment]
Thanks, @eladsegal ! 🙏

**Comment by eladsegal** [comment]
Done!
